compute_environment: LOCAL_MACHINE
debug: true
gpu_ids: "1"
distributed_type: NO
mixed_precision: 'bf16'
num_machines: 1
num_processes: 1
machine_rank: 0
main_training_function: main
downcast_bf16: 'no'
enable_cpu_affinity: false
rdzv_backend: static
same_network: true
use_cpu: false
